-- MySQL Script generated by MySQL Workbench
-- Friday 22 June 2018 01:12:36 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`setting` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `key` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `label` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `value` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `widget` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `widget_description` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL,
  `last_name` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `user` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `password` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_group` INT(11) NOT NULL,
  `status` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `version` INT(11) NOT NULL DEFAULT '0',
  `last_login` DATETIME NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` USING BTREE (`user` ASC, `email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hotel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `address` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `city` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `state` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `zip` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `phone` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interest` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `interest` VARCHAR(200) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`language` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  UNIQUE INDEX `language` (`language` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `weight` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
